### ISSUE TITLE
shall we add second to the model while click `Current Time`

### ISSUE THREAD

**Issue by marrypen** [ng2-ui/datetime-picker#181]
After setting `date-format="YYYY-MM-DD hh:mm:ss"`, the value with second defined in **component** can be correctly formatted.

But while click `Current Time`, the value will be formatted to `YYYY-MM-DD hh:mm:00`. **mention** that the second is always 00. Are there any specific reasons for this?

**Comment by allenhwkim** [comment]
@marrypen I have never thought of selecting a second when selecting date/time.

Is there any use case we need to select a second?
 For current time, yes the second is `00`, but it's just we simply did not consider second. 

Should we really consider second?

**Comment by marrypen** [comment]
sorry for the late response.

Thanks for the explanation. 
Forget the selection about second(this is not necessary I think), I was just wondering that we could correctly format date with second but by click `current time`, we can only get current-time without second.

**Comment by allenhwkim** [comment]
@marrypen when you click current time, we set hour and minute as the current time without considering second. I do not recommend to consider second for the current time because you have never choose second, and the second you clicked is different from the second you chose. Thus, unless there is clear reason we MUST chose second, I don't think this is a valid concern.

**Comment by marrypen** [comment]
@allenhwkim ok, got it. thanks again for the explanation.
